permalink: /:year/:month/:day/:title.html
highlighter: 'pygments'
theme: jekyll-whiteglass
paginate_path: /posts/:num/
paginate: 5
exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
plugins:
  - jekyll-paginate
  - jekyll-timeago

title: Uncertain by Principle
author:
  name: Stephen Demjanenko
  email: sdemjanenko@gmail.com
  github: github.com/sdemjanenko

jekyll_timeago:
  depth: 1
  suffix: ''

picture:
  source: "assets/images/fullsize"
  output: "assets/images/generated"
