permalink: /:year/:month/:day/:title
auto: false
pygments: true
paginate: 10
exclude: ['public', 'bin', 'vendor', 'Gemfile', 'Gemfile.lock', 'Procfile', 'Rakefile', 'unicorn.rb', 'config.ru', 'README.md']
destination: 'public'

title : Uncertain by Principle
author:
  name: Stephen Demjanenko
  email: sdemjanenko@gmail.com
